### ISSUE TITLE
minlist  empty

### ISSUE THREAD

**Issue by aleksandrmelnyk** [balint42/diff.js#2]
var arr = [342.8288930594771, 342.8288930594771, 338.76758026241794, 338.0099495756569, 338.90158296891985, 342.4320388902213, 342.4320388902213];
extrema(arr, 0.01) gives empty result, while am expecting it should provide at least 338.0099495756569 in minlist ...? Or misunderstood somth?

**Comment by balint42** [comment]
I cannot confirm the issue - please see this example: [https://jsfiddle.net/87zse4ar/](https://jsfiddle.net/87zse4ar/)

As it should `extrema` returns an object with two properties: `minlist` and `maxlist` both of which are arrays containing indices of the input array. `maxlist` is empty as it should be (since there is no local maximum) and `minlist` contains the index `3` as this is the index with the minimum value in the input array.

**Comment by mamayoleksandr** [comment]
Ah yep, my bad, sorry.
Seems to be working as expected.
